# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20180224_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
