# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_auto_20180225_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PackageValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='packagerental',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.PackageValue'),
        ),
        migrations.AddField(
            model_name='packagerental',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Rental'),
        ),
    ]
