# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_auto_20180226_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerental',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
