# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_auto_20180227_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.PackageRental'),
        ),
        migrations.AlterField(
            model_name='packagevalue',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
