# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_auto_20180228_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(verbose_name='end date'),
        ),
    ]
