# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_auto_20180228_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='agree_to_tc',
            field=models.BooleanField(default=False),
        ),
    ]
