# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_rental_agree_to_tc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='person',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='person',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='person',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='person',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='person',
        ),
        migrations.AddField(
            model_name='relationship',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='rentals.Customer'),
            preserve_default=False,
        ),
    ]
