# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_auto_20180228_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='brand',
            new_name='make',
        ),
        migrations.AddField(
            model_name='gear',
            name='category',
            field=models.CharField(default='fooBar', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gear',
            name='color',
            field=models.CharField(default='Rainbow', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gear',
            name='model',
            field=models.CharField(default='BarBaz', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gear',
            name='weight_range',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gear',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
