# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_auto_20180412_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='agree_to_tc',
        ),
    ]
