# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_remove_rental_agree_to_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='serial',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
